const teamNames = new Set([
  "Dolphins",
  "Bills",
  "Patriots",
  "Jets",
  "Browns",
  "Bengals",
  "Steelers",
  "Ravens",
  "Jaguars",
  "Colts",
  "Titans",
  "Texans",
  "Chargers",
  "Broncos",
  "Raiders",
  "Cheifs",
  "Eagles",
  "Cowboys",
  "Giants",
  "Washington",
  "Lions",
  "Bears",
  "Vikings",
  "Packers",
  "Falcons",
  "Buccaneers",
  "Saints",
  "Panthers",
  "Cardinals",
  "49ers",
  "Seahawks",
  "Rams",
]);

module.exports = { teamNames: teamNames };
